version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=APP1
    ports:
      - "3001:3000"  # Maps host port 3001 to container port 3000

  app2:
    build: .
    environment:
      - APP_NAME=APP2
    ports:
      - "3002:3000"  # Mapping container port 3001 to host port 3002

  app3:
    build: .
    environment:
      - APP_NAME=APP3
    ports:
      - "3003:3000"  # Mapping container port 3002 to host port 3003
